apiVersion: apps/v1
kind: Deployment
metadata:
  name: bqstoragereadclient-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bqstoragereadclient-0
  template:
      metadata:
        labels:
          app: bqstoragereadclient-0
      spec:
        containers:
        - name: bqstoragereadclient-0
          image: gcr.io/level-approach-382012/bq_storage_reader_client_0:latest
